name: Python Tests

# Workflow will run when you push changes or open a pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# The job that will run the tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies (pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest
